### ISSUE TITLE
Ifrastructure Presentation Img

### ISSUE THREAD

**Issue by marc101101** [C0rvus/python_ws1516#27]

**Comment by C0rvus** [comment]
Quote from Grips:
Am 13.1.16, am 20.1.16, am 27.1.16 und am 3.2.16 werden die (soweit vorliegenden) Ergebnisse präsentiert. Ein Vortrag soll 15-20 Minuten dauern.

**Comment by marc101101** [comment]
![image](https://cloud.githubusercontent.com/assets/6153088/12007601/ad0254b2-ac0b-11e5-93d8-18e761be39b3.png)

**Comment by marc101101** [comment]
![image](https://cloud.githubusercontent.com/assets/6153088/12007602/bc068154-ac0b-11e5-9174-7fa0b7daa638.png)

**Comment by marc101101** [comment]
![image](https://cloud.githubusercontent.com/assets/6153088/12007603/ca6a61a2-ac0b-11e5-8738-69c12653ace0.png)

**Comment by marc101101** [comment]
![image](https://cloud.githubusercontent.com/assets/6153088/12007610/f1d30ffa-ac0b-11e5-8371-623681c61a1b.png)
